class TestData:

    DOMAIN_URL = "https://scrapyards.vercel.app/"
    BASE_URL = DOMAIN_URL + "auth/login"
    ADMIN_EMAIL = "jainisha.r@aarchik.com"
    ADMIN_PASSWORD = "Admin@123"
    BROKER_EMAIL = "harshul.p@aarchik.com"
    BROKER_PASSWORD = "Admin@123"

    ERROR_MSG = ["Email is required!", "Password is required!"]
    PLACEHOLDER = ["Enter email", "Enter password"]

    # Login Messages
    EMAIL_FAIL_MSG = "Email is invalid"
    PASSWORD_FAIL_MSG = "Password is Invalid"
    SUCCESS_LOGIN = "Logged in successfully"
    DATA_ADD_MSG = "Data added successfully"
    DATA_UPDATE_MSG = "Data updated successfully"
    DATA_DELETE_MSG = "Data deleted successfully."

    PAGE_TITLE = "Scrapyard"

    # URL List
    DASHBOARD_URL = DOMAIN_URL + "dashboard"
    MATCATEGORY_URL = DOMAIN_URL + "material-category"
    MAT_URL = DOMAIN_URL + "materials"
    COUNTRY_URL = DOMAIN_URL + "country"
    CONTAINERS_URL = DOMAIN_URL + "containers"
    PLANT_URL = DOMAIN_URL + "plant"
    SHIPPING_LINE_URL = DOMAIN_URL + "shipping-line"
    PORTS_URL = DOMAIN_URL + "ports"
    SUPGROUP_URL = DOMAIN_URL + "supplier-group"
    SUPCOMPANY_URL = DOMAIN_URL + "supplier-company"
    SUPEMP_URL = DOMAIN_URL + "supplier-employee"
    BUYGROUP_URL = DOMAIN_URL + "buyer-group"
    BUYEMP_URL = DOMAIN_URL + "buyer_employee"
    BUYCOMPANY_URL = DOMAIN_URL + "buyer-company"
    QUALITY_URL = DOMAIN_URL + "quality-type"
    PAYTERMS_URL = DOMAIN_URL + "payment-terms"
    IMPURITY_URL = DOMAIN_URL + "impurity-tolerance"

    # Require Meaasges
    NAME_REQUIRE = "Name is required!"
    MAT_CAT_REQUIRE = "Material Category is required!"
    HS_CODE_REQUIRE = "Hs code is required!"
    ADDRESS_REQUIRE = "Address is required!"
    OFFLOADING_REQUIRE = "Offloading Capacity is required!"
    PRODUCTION_REQUIRE = "Production Capacity is required!"
    PORT_REQUIRE = "Port is required!"
    PAY_TERM_REQUIRE = "Payment Terms is required!"
    IMPURITY_REQUIRE = "Impurity Tolerance is required!"
    SUPGUP_REQUIRE = "Supplier Group is required!"
    COUNTRY_REQUIRE = "Country is required!"
    TAX_REQUIRE = "Tax ID No is required!"
    EXPORTER_REQUIRE = "Exporter ID No is required!"
    GST_REQUIRE = "VAT/GST is required!"
    SUPCOM_REQUIRE = "Supplier Company is required!"
    FNAME_REQUIRE = "First Name is required!"
    LNAME_REQUIRE = "Last Name is required!"
    DESIGNATION_REQUIRE = "Designation is required!"
    PASSWORD_REQUIRE = "Password is required!"
    BUYGUP_NAME_REQUIRE = "Buyer Group Name is required!"
    BUYGUP1_REQUIRE = "Buyer Group is required!"
    BUYCOM_REQUIRE = "Buyer Company is required!"
    EMAIL_REQUIRE = "Email is required!"
    BUYCOMNAME_REQUIRE = "Buyer Company Name is required!"

    # Field placeholders List
    MAT_CAT_PLACEHOLDER = "Enter Material category name"
    MAT_NAME_PLACEHOLDER = "Enter material name"
    MAT_HSCODE_PLACEHOLDER = "Enter Hs code"
    COUNTRY_PLACEHOLDER = "Enter country of origin name"
    CONTAINER_PLACEHOLDER = "Enter container name"
    ADDRESS_PLACEHOLDER = "Enter address"
    OFF_CAPACITY_PLACEHOLDER = "Enter capacity"
    PRODUCTION_PLACEHOLDER = "Enter Production Capacity"
    NAME_PLACEHOLDER = "Enter name"
    LINK_PLACEHOLDER = "Enter tracking link"
    API_PLACEHOLDER = "Enter api key"
    PORT_PLACEHOLDER = "Enter port name"
    DESC_PLACEHOLDER = "Enter description"
    PAYTERMS_PLACEHOLDER = "Enter Payment Terms "
    IMPURITY_PLACEHOLDER = "Enter Impurity Tolerance"
    SUPGUP_PLACEHOLDER = "Enter Supplier Group"
    SUP_COM_PLACEHOLDER = "Enter Supplier Company name"
    TAX_PLACEHOLDER = "Enter Tax ID No"
    EXPORTER_PLACEHOLDER = "Enter Exporter ID No"
    GST_PLACEHOLDER = "Enter VAT/GST"
    FNAME_PLACEHOLDER = "Enter First Name"
    LNAME_PLACEHOLDER = "Enter Last Name"
    DESIGNATION_PLACEHOLDER = "Enter Designation"
    PASSWORD_PLACEHOLDER = "Enter Password"
    ROLE_PLACEHOLDER = "Enter role"
    BUYGUP_PLACEHOLDER = "Enter Buyer Name Group"
    BUYCOM_PLACEHOLDER = "Enter Buyer Company name"
    EMAIL_PLACEHOLDER = "Enter Email "
