# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -rA
    - name: pytest-reporter
      # You may pin to the exact commit or the version.
      # uses: dima-engineer/pytest-reporter@9c75a90e04ac7122e7f8c391869b05e6ebf67e85
      uses: dima-engineer/pytest-reporter@v2.1.1
      with:
        # Path to the requirements file if you use pip. ./requirements.txt by default
        requirements-file: ./requirements.txt
        # root directory to recursively search for .py files
        # pytest-root-dir: # optional, default is .
        # directory with pytest tests. if left empty will identify test(s) dir by default
        # pytest-tests-dir: # optional, default is ./
        # list of directories and/or files to ignore
        # cov-omit-list: # optional, default is 
        # fail if any single file coverage is less than threshold
        # cov-threshold-single: # optional, default is 0
        # fail if the total coverage is less than threshold
        # cov-threshold-total: # optional, default is 0
        # Add support for async tests
        # async-tests: # optional
        # Version of poetry. Latest if not specified.
        # poetry-version: # optional
